import os
import io
from PIL import Image
from rembg import remove

source_dir = r"C:\Users\xl246\.gemini\antigravity-ide\brain\1c50a577-6182-472b-be1c-29d41123f22e"
target_dir = r"d:\LsLife\android\app\src\main\res\drawable"

files_to_process = [
    ("house_rent_icon_1786111977800.png", "ic_category_sub_house_rent_v2.webp"),
    ("office_rent_icon_1786112000342.png", "ic_category_sub_office_v2.webp"),
    ("warehouse_rent_icon_1786112013006.png", "ic_category_sub_warehouse_rent_v2.webp"),
    ("short_term_rent_icon_1786112026635.png", "ic_category_sub_short_term_rent_v2.webp"),
    ("parking_rent_icon_1786112041491.png", "ic_category_sub_parking_rent_v2.webp")
]

for src, dst in files_to_process:
    src_path = os.path.join(source_dir, src)
    dst_path = os.path.join(target_dir, dst)
    
    print(f"Processing {src} -> {dst}")
    
    with open(src_path, 'rb') as i:
        input_data = i.read()
    
    output_data = remove(input_data)
    
    img = Image.open(io.BytesIO(output_data)).convert("RGBA")
    
    # Crop to bounding box of content (removes extra empty space generated by rembg)
    bbox = img.getbbox()
    if bbox:
        img = img.crop(bbox)
        
    img_resized = img.resize((256, 256), Image.Resampling.LANCZOS)
    
    img_resized.save(dst_path, format="WEBP", quality=85)
    print(f"Saved {dst_path}")
