package com.lianshan.lslife.ui.navigation

object Routes {
    const val LOGIN = "login"
    const val FORGOT_PASSWORD = "forgot_password"
    const val HOME = "home"
    const val ORDERS = "orders"
    const val PUBLISH = "publish?postId={postId}&categoryId={categoryId}"
    const val MY_POSTS = "my_posts"
    const val CART = "cart"
    const val PROFILE = "profile"
    const val WALLET = "wallet"
    const val SETTINGS = "settings"
    const val ABOUT = "about"
    const val PRIVACY = "privacy"
    const val MERCHANT = "merchant/{merchantId}"
    const val ORDER_TRACK = "order_track/{orderId}"
    const val PERSONAL_INFO = "personal_info"
    const val EDIT_PROFILE = "edit_profile"
    const val MEMBERSHIP = "membership"
    const val MERCHANT_CERTIFY = "merchant_certify"
    const val PUBLIC_PROFILE = "public_profile/{userId}"
    const val ADDRESS_LIST = "address_list"
    const val ADDRESS_EDIT = "address_edit?addressId={addressId}"
    const val MESSAGE_LIST = "message_list"
    const val CATEGORY = "category"
    const val REAL_NAME_AGREEMENT = "real_name_agreement"
    const val REAL_NAME_AUTH = "real_name_auth/{signature}"
    const val CROP_AVATAR = "crop_avatar"
    const val CHAT = "chat/{sessionId}/{targetUserId}/{targetName}?initPostId={initPostId}"
    const val SEARCH = "search"
    const val POST_DETAIL = "post_detail/{postId}"
    const val CATEGORY_DETAIL = "category_detail/{categoryId}/{categoryName}"

    const val CHECKOUT = "checkout?merchantId={merchantId}&sellerId={sellerId}&entryIds={entryIds}&deliveryMethod={deliveryMethod}"

    fun merchant(id: String) = "merchant/$id"
    fun publicProfile(userId: String) = "public_profile/$userId"
    fun postDetail(id: String) = "post_detail/$id"
    fun orderTrack(id: String) = "order_track/$id"
    fun addressEdit(addressId: String? = null) =
        if (addressId.isNullOrBlank()) "address_edit?addressId=" else "address_edit?addressId=$addressId"
    fun cropAvatar() = "crop_avatar"
    fun chat(sessionId: String, targetUserId: String, targetName: String, initPostId: String? = null) = 
        "chat/$sessionId/$targetUserId/$targetName" + if (!initPostId.isNullOrBlank()) "?initPostId=$initPostId" else ""
    fun publish(postId: String? = null, categoryId: String? = null) = 
        if (postId.isNullOrBlank() && categoryId.isNullOrBlank()) "publish" 
        else "publish?postId=${postId ?: ""}&categoryId=${categoryId ?: ""}"
    fun checkout(merchantId: String?, sellerId: String?, entryIds: String?, deliveryMethod: String? = null) = "checkout?merchantId=${merchantId ?: ""}&sellerId=${sellerId ?: ""}&entryIds=${entryIds ?: ""}&deliveryMethod=${deliveryMethod ?: "DELIVERY"}"
    fun realNameAuth(signature: String) = "real_name_auth/$signature"
    fun categoryDetail(categoryId: String, categoryName: String) = "category_detail/$categoryId/${java.net.URLEncoder.encode(categoryName, "UTF-8")}"
}
